/* =========================================================
   LÓGICA DEL CATÁLOGO
   ========================================================= */

   let TODOS_LOS_PRODUCTOS = [];
   let CATEGORIA_ACTIVA = "Todos";
   let PRODUCTO_DETALLE_ACTUAL = null;
   let INDICE_GALERIA_ACTUAL = 0;

   const CATEGORIAS_BASE = ["Todos","Hombre","Mujer","Niños","Bebé","Hogar","Ferretería","Electrónico","Salud","Papelería","Mascotas","Belleza","Alimentos","Calzados","Bolsos","Juguetes","Tecnología"];

   function formatearPrecio(n){
     n = Number(n) || 0;
       return "$" + n.toLocaleString("es-CO", {minimumFractionDigits:0, maximumFractionDigits:0});
       }

       /* ---------------------------------------------------------
          NAVEGACIÓN ENTRE PANTALLA PRINCIPAL Y PERFIL
          --------------------------------------------------------- */
          function irAInicio(){
            mostrarPantalla("pantalla-catalogo");
              marcarNavActivo("inicio");
                if(TODOS_LOS_PRODUCTOS.length === 0){
                    cargarProductos();
                      }
                      }

                      function marcarNavActivo(nombre){
                        document.querySelectorAll(".nav-item").forEach(boton => {
                            boton.classList.toggle("activo", boton.dataset.nav === nombre);
                              });
                              }

                              /* ---------------------------------------------------------
                                 CARGAR PRODUCTOS DESDE FIREBASE
                                    Cada producto puede tener, además de los datos básicos:
                                       - imagenes: varias URLs separadas por coma (para la
                                            galería del detalle). Si no existe, se usa "imagen".
                                               - video: una URL de un video corto (10-20 seg).
                                               --------------------------------------------------------- */
                                               function cargarProductos(){
                                                 document.getElementById("grid-productos").innerHTML = '<div class="cargando"><div class="spinner"></div>Cargando productos...</div>';

                                                   db.ref("Productos").once("value").then(snap => {
                                                       const datos = snap.val() || {};
                                                           TODOS_LOS_PRODUCTOS = Object.keys(datos).map(codigo => {
                                                                 const p = datos[codigo];
                                                                       return {
                                                                               codigo: codigo,
                                                                                       nombre: p.nombre || "Producto",
                                                                                               precio: Number(p.precio || 0),
                                                                                                       categoria: p.categoria || "Otros",
                                                                                                               descripcion: p.descripcion || "",
                                                                                                                       imagen: p.imagen || "",
                                                                                                                               imagenes: p.imagenes || "",
                                                                                                                                       video: p.video || ""
                                                                                                                                             };
                                                                                                                                                 });
                                                                                                                                                     construirCategorias();
                                                                                                                                                         renderizarProductos();
                                                                                                                                                           }).catch(() => {
                                                                                                                                                               document.getElementById("grid-productos").innerHTML = "";
                                                                                                                                                                   const vacio = document.getElementById("mensaje-vacio");
                                                                                                                                                                       vacio.style.display = "block";
                                                                                                                                                                           vacio.textContent = "No pudimos cargar el catálogo. Revisá tu conexión.";
                                                                                                                                                                             });
                                                                                                                                                                             }

                                                                                                                                                                             /* Devuelve la lista de imágenes de un producto, sin importar
                                                                                                                                                                                si viene en "imagenes" (varias, separadas por coma) o
                                                                                                                                                                                   solo en "imagen" (una sola). */
                                                                                                                                                                                   function obtenerImagenesProducto(producto){
                                                                                                                                                                                     if(producto.imagenes && producto.imagenes.trim() !== ""){
                                                                                                                                                                                         return producto.imagenes.split(",").map(url => url.trim()).filter(url => url !== "");
                                                                                                                                                                                           }
                                                                                                                                                                                             if(producto.imagen && producto.imagen.trim() !== ""){
                                                                                                                                                                                                 return [producto.imagen.trim()];
                                                                                                                                                                                                   }
                                                                                                                                                                                                     return [];
                                                                                                                                                                                                     }

                                                                                                                                                                                                     /* ---------------------------------------------------------
                                                                                                                                                                                                        CATEGORÍAS
                                                                                                                                                                                                        --------------------------------------------------------- */
                                                                                                                                                                                                        function construirCategorias(){
                                                                                                                                                                                                          const presentes = new Set(TODOS_LOS_PRODUCTOS.map(p => p.categoria));
                                                                                                                                                                                                            const categorias = CATEGORIAS_BASE.filter(c => c === "Todos" || presentes.has(c));

                                                                                                                                                                                                              const contenedor = document.getElementById("lista-categorias");
                                                                                                                                                                                                                contenedor.innerHTML = categorias.map(c =>
                                                                                                                                                                                                                    `<button class="chip-cat ${c===CATEGORIA_ACTIVA?'activo':''}" onclick="seleccionarCategoria('${c.replace(/'/g,"\\'")}')">${c}</button>`
                                                                                                                                                                                                                      ).join("");
                                                                                                                                                                                                                      }

                                                                                                                                                                                                                      function seleccionarCategoria(categoria){
                                                                                                                                                                                                                        CATEGORIA_ACTIVA = categoria;
                                                                                                                                                                                                                          document.querySelectorAll(".chip-cat").forEach(chip => {
                                                                                                                                                                                                                              chip.classList.toggle("activo", chip.textContent === categoria);
                                                                                                                                                                                                                                });
                                                                                                                                                                                                                                  document.getElementById("titulo-seccion").textContent = categoria === "Todos" ? "Todos los productos" : categoria;
                                                                                                                                                                                                                                    filtrarProductos();
                                                                                                                                                                                                                                    }

                                                                                                                                                                                                                                    /* ---------------------------------------------------------
                                                                                                                                                                                                                                       BÚSQUEDA — por nombre, descripción o categoría
                                                                                                                                                                                                                                          Si hay texto escrito, busca en TODO el catálogo, sin
                                                                                                                                                                                                                                             importar qué categoría esté tildada arriba.
                                                                                                                                                                                                                                             --------------------------------------------------------- */
                                                                                                                                                                                                                                             function filtrarProductos(){
                                                                                                                                                                                                                                               const texto = document.getElementById("input-buscar").value.trim().toLowerCase();

                                                                                                                                                                                                                                                 if(texto){
                                                                                                                                                                                                                                                     const resultado = TODOS_LOS_PRODUCTOS.filter(p =>
                                                                                                                                                                                                                                                           p.nombre.toLowerCase().includes(texto) ||
                                                                                                                                                                                                                                                                 p.descripcion.toLowerCase().includes(texto) ||
                                                                                                                                                                                                                                                                       p.categoria.toLowerCase().includes(texto)
                                                                                                                                                                                                                                                                           );
                                                                                                                                                                                                                                                                               renderizarProductos(resultado);
                                                                                                                                                                                                                                                                                   return;
                                                                                                                                                                                                                                                                                     }

                                                                                                                                                                                                                                                                                       // Sin texto de búsqueda: se respeta la categoría elegida
                                                                                                                                                                                                                                                                                         let lista = TODOS_LOS_PRODUCTOS;
                                                                                                                                                                                                                                                                                           if(CATEGORIA_ACTIVA !== "Todos"){
                                                                                                                                                                                                                                                                                               lista = lista.filter(p => p.categoria === CATEGORIA_ACTIVA);
                                                                                                                                                                                                                                                                                                 }
                                                                                                                                                                                                                                                                                                   renderizarProductos(lista);
                                                                                                                                                                                                                                                                                                   }

                                                                                                                                                                                                                                                                                                   /* ---------------------------------------------------------
                                                                                                                                                                                                                                                                                                      DIBUJAR LAS TARJETAS (estilo mosaico)
                                                                                                                                                                                                                                                                                                      --------------------------------------------------------- */
                                                                                                                                                                                                                                                                                                      function renderizarProductos(lista){
                                                                                                                                                                                                                                                                                                        lista = lista || TODOS_LOS_PRODUCTOS;
                                                                                                                                                                                                                                                                                                          const grid = document.getElementById("grid-productos");
                                                                                                                                                                                                                                                                                                            const vacio = document.getElementById("mensaje-vacio");

                                                                                                                                                                                                                                                                                                              if(lista.length === 0){
                                                                                                                                                                                                                                                                                                                  grid.innerHTML = "";
                                                                                                                                                                                                                                                                                                                      vacio.style.display = "block";
                                                                                                                                                                                                                                                                                                                          vacio.textContent = "No encontramos productos con esa búsqueda 🔍";
                                                                                                                                                                                                                                                                                                                              return;
                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                  vacio.style.display = "none";

                                                                                                                                                                                                                                                                                                                                    grid.innerHTML = lista.map(p => {
                                                                                                                                                                                                                                                                                                                                        const imagenes = obtenerImagenesProducto(p);
                                                                                                                                                                                                                                                                                                                                            const primeraImagen = imagenes[0] || "";
                                                                                                                                                                                                                                                                                                                                                return `
                                                                                                                                                                                                                                                                                                                                                    <div class="tarjeta-producto" onclick="abrirDetalle('${p.codigo}')">
                                                                                                                                                                                                                                                                                                                                                          <div class="imagen-wrap">
                                                                                                                                                                                                                                                                                                                                                                  ${primeraImagen ? `<img src="${primeraImagen}" alt="${p.nombre}" loading="lazy">` : ''}
                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                              <div class="info-producto">
                                                                                                                                                                                                                                                                                                                                                                                      <div class="nombre-producto">${p.nombre}</div>
                                                                                                                                                                                                                                                                                                                                                                                              <div class="fila-precio-boton">
                                                                                                                                                                                                                                                                                                                                                                                                        <div class="precio-producto">${formatearPrecio(p.precio)}</div>
                                                                                                                                                                                                                                                                                                                                                                                                                  <button class="boton-agregar-mini" onclick="event.stopPropagation(); agregarAlCarrito('${p.codigo}', 1)">+</button>
                                                                                                                                                                                                                                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                  <div class="categoria-producto">${p.categoria}</div>
                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>`;
                                                                                                                                                                                                                                                                                                                                                                                                                                              }).join("");
                                                                                                                                                                                                                                                                                                                                                                                                                                              }

                                                                                                                                                                                                                                                                                                                                                                                                                                              /* ---------------------------------------------------------
                                                                                                                                                                                                                                                                                                                                                                                                                                                 DETALLE DE PRODUCTO — galería, video y relacionados
                                                                                                                                                                                                                                                                                                                                                                                                                                                 --------------------------------------------------------- */
                                                                                                                                                                                                                                                                                                                                                                                                                                                 function abrirDetalle(codigo){
                                                                                                                                                                                                                                                                                                                                                                                                                                                   const producto = TODOS_LOS_PRODUCTOS.find(p => p.codigo === codigo);
                                                                                                                                                                                                                                                                                                                                                                                                                                                     if(!producto) return;
                                                                                                                                                                                                                                                                                                                                                                                                                                                       PRODUCTO_DETALLE_ACTUAL = codigo;

                                                                                                                                                                                                                                                                                                                                                                                                                                                         document.getElementById("detalle-precio").textContent = formatearPrecio(producto.precio);
                                                                                                                                                                                                                                                                                                                                                                                                                                                           document.getElementById("detalle-nombre").textContent = producto.nombre;
                                                                                                                                                                                                                                                                                                                                                                                                                                                             document.getElementById("detalle-categoria").textContent = producto.categoria;
                                                                                                                                                                                                                                                                                                                                                                                                                                                               document.getElementById("detalle-descripcion").textContent = producto.descripcion || "Sin descripción disponible.";

                                                                                                                                                                                                                                                                                                                                                                                                                                                                 // Video corto (si el producto tiene uno cargado)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                   const videoWrap = document.getElementById("video-producto-wrap");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                     const video = document.getElementById("video-producto");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                       if(producto.video && producto.video.trim() !== ""){
                                                                                                                                                                                                                                                                                                                                                                                                                                                                           video.src = producto.video.trim();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                               videoWrap.style.display = "block";
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 } else {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     video.removeAttribute("src");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         videoWrap.style.display = "none";
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             // Galería de fotos
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               const imagenes = obtenerImagenesProducto(producto);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 const galeria = document.getElementById("galeria-imagenes");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   const puntos = document.getElementById("galeria-puntos");

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     if(imagenes.length === 0){
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         galeria.innerHTML = "";
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             puntos.innerHTML = "";
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               } else {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   galeria.innerHTML = imagenes.map(url => `<img src="${url}" alt="${producto.nombre}">`).join("");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       puntos.innerHTML = imagenes.length > 1
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             ? imagenes.map((_, i) => `<span class="${i===0?'activo':''}"></span>`).join("")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   : "";
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       // Cuando el usuario desliza la galería, actualizamos el puntito activo
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         galeria.onscroll = function(){
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             const ancho = galeria.clientWidth;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 const indice = Math.round(galeria.scrollLeft / ancho);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     document.querySelectorAll("#galeria-puntos span").forEach((punto, i) => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           punto.classList.toggle("activo", i === indice);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 };

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   renderizarRelacionados(producto);

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     document.getElementById("overlay-detalle").classList.add("visible");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     /* Productos de la misma categoría, para "también te puede interesar" */
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     function renderizarRelacionados(productoActual){
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       const relacionados = TODOS_LOS_PRODUCTOS
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           .filter(p => p.categoria === productoActual.categoria && p.codigo !== productoActual.codigo)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               .slice(0, 8);

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 const contenedor = document.getElementById("fila-relacionados");

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   if(relacionados.length === 0){
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       contenedor.innerHTML = `<p style="font-size:12.5px; color:var(--texto-suave);">No hay más productos en esta categoría todavía.</p>`;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           return;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               contenedor.innerHTML = relacionados.map(p => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   const imagenes = obtenerImagenesProducto(p);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       const imagen = imagenes[0] || "";
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           return `
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               <div class="tarjeta-relacionada" onclick="abrirDetalle('${p.codigo}')">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     ${imagen ? `<img src="${imagen}" alt="${p.nombre}">` : `<div style="width:120px;height:120px;border-radius:12px;background:var(--linea);"></div>`}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           <div class="nombre-rel">${p.nombre}</div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 <div class="precio-rel">${formatearPrecio(p.precio)}</div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     </div>`;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       }).join("");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       function cerrarOverlay(id){
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         document.getElementById(id).classList.remove("visible");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           // Si cerramos el detalle, pausamos el video para que no
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             // siga sonando/reproduciéndose de fondo.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               if(id === "overlay-detalle"){
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   const video = document.getElementById("video-producto");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       video.pause();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         