/* =========================================================
   LÓGICA DE LOGIN Y REGISTRO
      (Ya no existe el modo invitado: hay que tener cuenta
         para ver el catálogo.)
         ========================================================= */

         let modoFormulario = "login";

         const EDAD_MINIMA = 18;

         /* ---------------------------------------------------------
            CAMBIAR DE PANTALLA
            --------------------------------------------------------- */
            function mostrarPantalla(idPantalla){
              document.querySelectorAll(".pantalla").forEach(p => p.classList.remove("visible"));
                document.getElementById(idPantalla).classList.add("visible");
                }

                /* ---------------------------------------------------------
                   FORMULARIO DE LOGIN / REGISTRO
                   --------------------------------------------------------- */
                   function mostrarFormulario(modo){
                     modoFormulario = modo;
                       actualizarTextosFormulario();
                         limpiarFormulario();
                           mostrarPantalla("pantalla-formulario");
                           }

                           function volverABienvenida(){
                             mostrarPantalla("pantalla-bienvenida");
                             }

                             function cambiarModo(){
                               modoFormulario = (modoFormulario === "login") ? "registro" : "login";
                                 actualizarTextosFormulario();
                                   limpiarFormulario();
                                   }

                                   function actualizarTextosFormulario(){
                                     const esRegistro = modoFormulario === "registro";

                                       document.getElementById("titulo-formulario").textContent = esRegistro ? "Crear cuenta" : "Iniciar sesión";
                                         document.getElementById("boton-enviar").textContent = esRegistro ? "Registrarme" : "Iniciar sesión";

                                           document.getElementById("campo-nombre").style.display = esRegistro ? "block" : "none";
                                             document.getElementById("campo-telefono").style.display = esRegistro ? "block" : "none";
                                               document.getElementById("campo-nacimiento").style.display = esRegistro ? "block" : "none";
                                                 document.getElementById("campo-sexo").style.display = esRegistro ? "block" : "none";
                                                   document.getElementById("campo-documento").style.display = esRegistro ? "block" : "none";
                                                     document.getElementById("campo-foto").style.display = esRegistro ? "block" : "none";
                                                       document.getElementById("fila-aceptar-terminos").style.display = esRegistro ? "flex" : "none";

                                                         document.getElementById("texto-alterno").innerHTML = esRegistro
                                                             ? '¿Ya tenés cuenta? <b onclick="cambiarModo()">Iniciar sesión</b>'
                                                                 : '¿No tenés cuenta? <b onclick="cambiarModo()">Registrate</b>';
                                                                 }

                                                                 function limpiarFormulario(){
                                                                   document.getElementById("mensaje-error").classList.remove("visible");
                                                                     document.getElementById("input-nombre").value = "";
                                                                       document.getElementById("input-telefono").value = "";
                                                                         document.getElementById("input-nacimiento").value = "";
                                                                           document.getElementById("input-sexo").value = "";
                                                                             document.getElementById("input-documento").value = "";
                                                                               document.getElementById("input-foto").value = "";
                                                                                 document.getElementById("input-email").value = "";
                                                                                   document.getElementById("input-password").value = "";
                                                                                     document.getElementById("check-terminos").checked = false;
                                                                                     }

                                                                                     function mostrarError(texto){
                                                                                       const el = document.getElementById("mensaje-error");
                                                                                         el.textContent = texto;
                                                                                           el.classList.add("visible");
                                                                                           }

                                                                                           function traducirError(codigo){
                                                                                             const mensajes = {
                                                                                                 "auth/invalid-email": "El correo no es válido.",
                                                                                                     "auth/user-not-found": "No existe una cuenta con ese correo.",
                                                                                                         "auth/wrong-password": "La contraseña es incorrecta.",
                                                                                                             "auth/invalid-credential": "Correo o contraseña incorrectos.",
                                                                                                                 "auth/email-already-in-use": "Ya existe una cuenta con ese correo.",
                                                                                                                     "auth/weak-password": "La contraseña debe tener al menos 6 caracteres.",
                                                                                                                         "auth/missing-password": "Ingresá una contraseña."
                                                                                                                           };
                                                                                                                             return mensajes[codigo] || "Ocurrió un error. Intentá de nuevo.";
                                                                                                                             }

                                                                                                                             /* Calcula la edad exacta a partir de una fecha de nacimiento
                                                                                                                                en formato "YYYY-MM-DD" (el que entrega <input type="date">) */
                                                                                                                                function calcularEdad(fechaTexto){
                                                                                                                                  const hoy = new Date();
                                                                                                                                    const nacimiento = new Date(fechaTexto);
                                                                                                                                      let edad = hoy.getFullYear() - nacimiento.getFullYear();
                                                                                                                                        const aunNoCumplioEsteAno =
                                                                                                                                            (hoy.getMonth() < nacimiento.getMonth()) ||
                                                                                                                                                (hoy.getMonth() === nacimiento.getMonth() && hoy.getDate() < nacimiento.getDate());
                                                                                                                                                  if(aunNoCumplioEsteAno) edad--;
                                                                                                                                                    return edad;
                                                                                                                                                    }

                                                                                                                                                    /* ---------------------------------------------------------
                                                                                                                                                       ENVIAR EL FORMULARIO (login o registro)
                                                                                                                                                       --------------------------------------------------------- */
                                                                                                                                                       function enviarFormulario(){
                                                                                                                                                         const email = document.getElementById("input-email").value.trim();
                                                                                                                                                           const password = document.getElementById("input-password").value;
                                                                                                                                                             const boton = document.getElementById("boton-enviar");

                                                                                                                                                               document.getElementById("mensaje-error").classList.remove("visible");

                                                                                                                                                                 if(!email || !password){
                                                                                                                                                                     mostrarError("Completá correo y contraseña.");
                                                                                                                                                                         return;
                                                                                                                                                                           }

                                                                                                                                                                             if(modoFormulario === "login"){
                                                                                                                                                                                 boton.disabled = true;
                                                                                                                                                                                     boton.textContent = "Ingresando...";

                                                                                                                                                                                         auth.signInWithEmailAndPassword(email, password)
                                                                                                                                                                                               .catch(error => mostrarError(traducirError(error.code)))
                                                                                                                                                                                                     .finally(() => {
                                                                                                                                                                                                             boton.disabled = false;
                                                                                                                                                                                                                     boton.textContent = "Iniciar sesión";
                                                                                                                                                                                                                           });

                                                                                                                                                                                                                             } else {
                                                                                                                                                                                                                                 const nombre = document.getElementById("input-nombre").value.trim();
                                                                                                                                                                                                                                     const telefono = document.getElementById("input-telefono").value.trim();
                                                                                                                                                                                                                                         const nacimiento = document.getElementById("input-nacimiento").value;
                                                                                                                                                                                                                                             const sexo = document.getElementById("input-sexo").value;
                                                                                                                                                                                                                                                 const documento = document.getElementById("input-documento").value.trim();
                                                                                                                                                                                                                                                     const foto = document.getElementById("input-foto").value.trim();
                                                                                                                                                                                                                                                         const aceptoTerminos = document.getElementById("check-terminos").checked;

                                                                                                                                                                                                                                                             if(!nombre){
                                                                                                                                                                                                                                                                   mostrarError("Ingresá tu nombre completo.");
                                                                                                                                                                                                                                                                         return;
                                                                                                                                                                                                                                                                             }
                                                                                                                                                                                                                                                                                 if(!telefono){
                                                                                                                                                                                                                                                                                       mostrarError("Ingresá tu teléfono.");
                                                                                                                                                                                                                                                                                             return;
                                                                                                                                                                                                                                                                                                 }
                                                                                                                                                                                                                                                                                                     if(!nacimiento){
                                                                                                                                                                                                                                                                                                           mostrarError("Ingresá tu fecha de nacimiento.");
                                                                                                                                                                                                                                                                                                                 return;
                                                                                                                                                                                                                                                                                                                     }
                                                                                                                                                                                                                                                                                                                         const edad = calcularEdad(nacimiento);
                                                                                                                                                                                                                                                                                                                             if(edad < EDAD_MINIMA){
                                                                                                                                                                                                                                                                                                                                   mostrarError("Tenés que ser mayor de " + EDAD_MINIMA + " años para crear una cuenta y hacer pedidos.");
                                                                                                                                                                                                                                                                                                                                         return;
                                                                                                                                                                                                                                                                                                                                             }
                                                                                                                                                                                                                                                                                                                                                 if(!sexo){
                                                                                                                                                                                                                                                                                                                                                       mostrarError("Seleccioná una opción en Sexo.");
                                                                                                                                                                                                                                                                                                                                                             return;
                                                                                                                                                                                                                                                                                                                                                                 }
                                                                                                                                                                                                                                                                                                                                                                     if(!documento){
                                                                                                                                                                                                                                                                                                                                                                           mostrarError("Ingresá tu número de identidad.");
                                                                                                                                                                                                                                                                                                                                                                                 return;
                                                                                                                                                                                                                                                                                                                                                                                     }
                                                                                                                                                                                                                                                                                                                                                                                         if(!aceptoTerminos){
                                                                                                                                                                                                                                                                                                                                                                                               mostrarError("Tenés que aceptar los Términos y Condiciones para crear tu cuenta.");
                                                                                                                                                                                                                                                                                                                                                                                                     return;
                                                                                                                                                                                                                                                                                                                                                                                                         }

                                                                                                                                                                                                                                                                                                                                                                                                             boton.disabled = true;
                                                                                                                                                                                                                                                                                                                                                                                                                 boton.textContent = "Creando cuenta...";

                                                                                                                                                                                                                                                                                                                                                                                                                     auth.createUserWithEmailAndPassword(email, password)
                                                                                                                                                                                                                                                                                                                                                                                                                           .then(credencial => {
                                                                                                                                                                                                                                                                                                                                                                                                                                   return db.ref("usuarios/" + credencial.user.uid).set({
                                                                                                                                                                                                                                                                                                                                                                                                                                             nombre: nombre,
                                                                                                                                                                                                                                                                                                                                                                                                                                                       telefono: telefono,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                 email: email,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                           nacimiento: nacimiento,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     sexo: sexo,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               documento: documento,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         foto: foto,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   direccion: "",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             ciudad: "",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       referencia: "",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 creado: Date.now()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               })
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     .catch(error => mostrarError(traducirError(error.code)))
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           .finally(() => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   boton.disabled = false;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           boton.textContent = "Registrarme";
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   /* ---------------------------------------------------------
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      CERRAR SESIÓN
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      --------------------------------------------------------- */
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      function cerrarSesionUsuario(){
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        auth.signOut();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        /* ---------------------------------------------------------
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           FIREBASE NOS AVISA SOLO cuando alguien inicia o cierra
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              sesión.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              --------------------------------------------------------- */
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              auth.onAuthStateChanged(usuario => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                if(usuario){
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    mostrarPantalla("pantalla-catalogo");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        marcarNavActivo("inicio");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            cargarProductos();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                actualizarBadgeCarrito();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  } else {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      mostrarPantalla("pantalla-bienvenida");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        